  spring:
    application:
      name: forum-service
    datasource:
      url: jdbc:postgresql://cohort5860-ans-cohort5860.h.aivencloud.com:10158/defaultdb
      username: avnadmin
      password: ${AIVEN_PASS}
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
    data:
      mongodb:
        uri: ${MONGO_URI}
    mail:
      host: smtp.gmail.com
      port: 587
      username: ${EMAIL}
      password: ${GMAIL_PASSWORD}
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true